name: Generate Hash

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate hash
        id: generate
        run: |
          HASH_VALUE=$(echo "mydata" | sha256sum | cut -d' ' -f1)
          echo "HASH=$HASH_VALUE" >> $GITHUB_OUTPUT

      - name: Trigger process workflow
        uses:
        with:
          workflow: process.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"hash": "${{ steps.generate.outputs.HASH }}"}'
