name: Process

on:
  workflow_dispatch:
    inputs:
      hash:
        description: "Hash to process"
        required: true

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Print the hash
        run: echo "Received hash: ${{ github.event.inputs.hash }}"
